import type { BudgetReport } from '../github/budget.js';
import { notificationLogPg, notificationLogSq } from '../db/schema.js';

export type NotificationChannel = 'slack' | 'github_issue';

export type NotificationResult = {
  success: boolean;
  channel: NotificationChannel;
  externalId?: string;
  errorMessage?: string;
};

export type SlackConfig = {
  webhookUrl: string;
  channel?: string;
  username?: string;
};

export type GitHubIssueConfig = {
  owner: string;
  repo: string;
  token: string;
};

export async function sendSlackNotification(
  db: any,
  config: SlackConfig,
  report: BudgetReport,
  snapshotDate: string,
): Promise<NotificationResult> {
  const payload = {
    channel: config.channel || '#alerts',
    username: config.username || 'BurnRate Bot',
    icon_emoji: ':warning:',
    attachments: [
      {
        color: report.alert_level === 'critical' ? 'danger' : report.alert_level === 'warning' ? 'warning' : 'good',
        title: `Budget Alert: ${report.alert_level?.toUpperCase()}`,
        fields: [
          { title: 'Total Budget', value: `$${report.total_budget.toFixed(2)}`, short: true },
          { title: 'Budget Used', value: `$${report.budget_used.toFixed(2)}`, short: true },
          { title: 'Budget Remaining', value: `$${report.budget_remaining.toFixed(2)}`, short: true },
          { title: '% Used', value: `${report.pct_used.toFixed(1)}%`, short: true },
          { title: '% Elapsed', value: `${report.pct_elapsed.toFixed(1)}%`, short: true },
        ],
        footer: `BurnRate Alert • ${snapshotDate}`,
      },
    ],
  };

  try {
    const response = await fetch(config.webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      throw new Error(`Slack webhook returned ${response.status} ${response.statusText}`);
    }

    await logNotification(db, {
      snapshotDate,
      channel: 'slack',
      notificationType: 'budget_alert',
      externalId: config.channel || 'default',
      payload,
      success: true,
    });

    return {
      success: true,
      channel: 'slack',
      externalId: config.channel || 'default',
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);

    await logNotification(db, {
      snapshotDate,
      channel: 'slack',
      notificationType: 'budget_alert',
      externalId: config.channel || 'default',
      payload,
      success: false,
      errorMessage,
    });

    return {
      success: false,
      channel: 'slack',
      errorMessage,
    };
  }
}

export async function sendGitHubIssue(
  db: any,
  config: GitHubIssueConfig,
  report: BudgetReport,
  snapshotDate: string,
): Promise<NotificationResult> {
  const title = `[BurnRate] Budget Alert: ${report.alert_level?.toUpperCase()} - ${snapshotDate}`;
  const body = `## Budget Status

| Metric | Value |
|--------|-------|
| Total Budget | $${report.total_budget.toFixed(2)} |
| Budget Used | $${report.budget_used.toFixed(2)} |
| Budget Remaining | $${report.budget_remaining.toFixed(2)} |
| % Used | ${report.pct_used.toFixed(1)}% |
| % Elapsed | ${report.pct_elapsed.toFixed(1)}% |
| Forecast 7d | $${report.forecast_7d?.toFixed(2) ?? 'N/A'} |
| Forecast 30d | $${report.forecast_30d?.toFixed(2) ?? 'N/A'} |

**Alert Level**: ${report.alert_level?.toUpperCase() || 'INFO'}

---
*Generated by BurnRate on ${snapshotDate}*`;

  const payload = {
    title,
    body,
    labels: ['budget', 'alert', report.alert_level || 'info'],
  };

  try {
    const response = await fetch(`https://api.github.com/repos/${config.owner}/${config.repo}/issues`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${config.token}`,
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2026-03-10',
        'Accept': 'application/vnd.github+json',
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`GitHub API returned ${response.status}: ${errorText}`);
    }

    const result = await response.json() as { number: number; html_url: string };

    await logNotification(db, {
      snapshotDate,
      channel: 'github_issue',
      notificationType: 'budget_alert',
      externalId: String(result.number),
      payload: { ...payload, url: result.html_url },
      success: true,
    });

    return {
      success: true,
      channel: 'github_issue',
      externalId: String(result.number),
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);

    await logNotification(db, {
      snapshotDate,
      channel: 'github_issue',
      notificationType: 'budget_alert',
      externalId: undefined,
      payload,
      success: false,
      errorMessage,
    });

    return {
      success: false,
      channel: 'github_issue',
      errorMessage,
    };
  }
}

async function logNotification(
  db: any,
  data: {
    snapshotDate: string;
    channel: NotificationChannel;
    notificationType: string;
    externalId?: string;
    payload: unknown;
    success: boolean;
    errorMessage?: string;
  },
): Promise<void> {
  const isPg = db.constructor.name.toLowerCase().includes('postgres');

  if (isPg) {
    await db.insert(notificationLogPg).values({
      snapshotDate: data.snapshotDate,
      channel: data.channel,
      notificationType: data.notificationType,
      externalId: data.externalId || null,
      payload: data.payload as any,
      success: data.success,
      errorMessage: data.errorMessage || null,
    }).onConflictDoNothing();
  } else {
    await db.insert(notificationLogSq).values({
      snapshotDate: data.snapshotDate,
      channel: data.channel,
      notificationType: data.notificationType,
      externalId: data.externalId || null,
      payload: data.payload as any,
      success: data.success ? 1 : 0,
      errorMessage: data.errorMessage || null,
    }).onConflictDoNothing();
  }
}
