import type { BurnRateAlert, NotificationProviderConfig } from '../types.js';
import { BaseProvider } from '../provider.js';
import { sanitizeErrorMessage } from '../sanitize.js';
import { GITHUB_API_VERSION } from '../../github/client.js';

export class GitHubIssuesProvider extends BaseProvider {
  readonly name = 'github_issue';

  private owner: string;
  private repo: string;
  private token: string;

  constructor(config: NotificationProviderConfig) {
    super(config.minLevel as BaseProvider['minLevel'] | undefined);
    this.owner = config.owner as string;
    this.repo = config.repo as string;
    this.token = config.token as string;
  }

  async send(alert: BurnRateAlert): Promise<{ success: boolean; externalId?: string; errorMessage?: string }> {
    const title = `[BurnRate] ${alert.subject}`;

    const data = alert.data;
    const statsLines: string[] = [];
    if (data.totalBudget !== undefined || data.budgetUsed !== undefined) {
      statsLines.push('| Metric | Value |', '|--------|-------|');
      if (data.totalBudget !== undefined) statsLines.push(`| Total Budget | $${Number(data.totalBudget).toFixed(2)} |`);
      if (data.budgetUsed !== undefined) statsLines.push(`| Budget Used | $${Number(data.budgetUsed).toFixed(2)} |`);
      if (data.budgetRemaining !== undefined) statsLines.push(`| Budget Remaining | $${Number(data.budgetRemaining).toFixed(2)} |`);
      if (data.pctUsed !== undefined) statsLines.push(`| % Used | ${Number(data.pctUsed).toFixed(1)}% |`);
      if (data.pctElapsed !== undefined) statsLines.push(`| % Elapsed | ${Number(data.pctElapsed).toFixed(1)}% |`);
      if (data.forecast7d !== undefined && data.forecast7d !== null) statsLines.push(`| Forecast 7d | $${Number(data.forecast7d).toFixed(2)} |`);
      if (data.forecast30d !== undefined && data.forecast30d !== null) statsLines.push(`| Forecast 30d | $${Number(data.forecast30d).toFixed(2)} |`);
    }
    const statsTable = statsLines.join('\n');

    const body = `## ${alert.subject}

${alert.body}

${statsTable}

**Alert Level**: ${alert.level.toUpperCase()}
**Persistent Days**: ${alert.persistentDays}

---
*Generated by BurnRate on ${alert.timestamp.toISOString()}*`;

    const payload = {
      title,
      body,
      labels: ['alert', ...new Set(alert.tags)],
    };

    const response = await fetch(`https://api.github.com/repos/${this.owner}/${this.repo}/issues`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${this.token}`,
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': GITHUB_API_VERSION,
        'Accept': 'application/vnd.github+json',
      },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(15000),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`GitHub API returned ${response.status}: ${sanitizeErrorMessage(errorText)}`);
    }

    const result = await response.json() as { number: number; html_url: string };
    return { success: true, externalId: String(result.number) };
  }
}
