import type { BurnRateAlert, NotificationProviderConfig } from '../types.js';
import { BaseProvider } from '../provider.js';

const GRAPH_BASE_URL = 'https://graph.microsoft.com/v1.0';

type GraphTokenResponse = {
  token_type: string;
  access_token: string;
  expires_in: number;
};

export class OutlookProvider extends BaseProvider {
  readonly name = 'outlook';

  private tenantId: string;
  private clientId: string;
  private clientSecret: string;
  private from: string;
  private to: string[];
  private accessToken: string | null = null;
  private tokenExpiresAt: number = 0;

  constructor(config: NotificationProviderConfig) {
    super(config.minLevel as BaseProvider['minLevel'] | undefined);
    this.tenantId = config.tenantId as string;
    this.clientId = config.clientId as string;
    this.clientSecret = config.clientSecret as string;
    this.from = config.from as string;
    this.to = (config.to as string[]);
  }

  async send(alert: BurnRateAlert): Promise<{ success: boolean; externalId?: string; errorMessage?: string }> {
    const htmlBody = this.buildHtmlBody(alert);

    const emailPayload = {
      message: {
        subject: alert.subject,
        body: {
          contentType: 'HTML',
          content: htmlBody,
        },
        from: {
          emailAddress: { address: this.from },
        },
        toRecipients: this.to.map((addr) => ({
          emailAddress: { address: addr },
        })),
      },
    };

    const token = await this.getToken();

    const response = await fetch(`${GRAPH_BASE_URL}/users/${encodeURIComponent(this.from)}/sendMail`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(emailPayload),
      signal: AbortSignal.timeout(15000),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Graph API returned ${response.status}: ${errorText.slice(0, 500)}`);
    }

    return { success: true, externalId: this.to.join(',') };
  }

  private buildHtmlBody(alert: BurnRateAlert): string {
    const data = alert.data;
    let statsHtml = '';
    if (data.totalBudget !== undefined || data.budgetUsed !== undefined) {
      statsHtml = '<table border="1" cellpadding="4" cellspacing="0" style="border-collapse:collapse">';
      if (data.totalBudget !== undefined) statsHtml += `<tr><td><b>Total Budget</b></td><td>$${Number(data.totalBudget).toFixed(2)}</td></tr>`;
      if (data.budgetUsed !== undefined) statsHtml += `<tr><td><b>Budget Used</b></td><td>$${Number(data.budgetUsed).toFixed(2)}</td></tr>`;
      if (data.budgetRemaining !== undefined) statsHtml += `<tr><td><b>Budget Remaining</b></td><td>$${Number(data.budgetRemaining).toFixed(2)}</td></tr>`;
      if (data.pctUsed !== undefined) statsHtml += `<tr><td><b>% Used</b></td><td>${Number(data.pctUsed).toFixed(1)}%</td></tr>`;
      if (data.pctElapsed !== undefined) statsHtml += `<tr><td><b>% Elapsed</b></td><td>${Number(data.pctElapsed).toFixed(1)}%</td></tr>`;
      if (data.forecast7d !== undefined && data.forecast7d !== null) statsHtml += `<tr><td><b>Forecast 7d</b></td><td>$${Number(data.forecast7d).toFixed(2)}</td></tr>`;
      if (data.forecast30d !== undefined && data.forecast30d !== null) statsHtml += `<tr><td><b>Forecast 30d</b></td><td>$${Number(data.forecast30d).toFixed(2)}</td></tr>`;
      statsHtml += '</table>';
    }

    return `<h2>${alert.subject}</h2>
<p>${alert.body}</p>
<p><b>Alert Level:</b> ${alert.level.toUpperCase()}</p>
<p><b>Persistent Days:</b> ${alert.persistentDays}</p>
${statsHtml}
<p><i>Generated by BurnRate on ${alert.timestamp.toISOString()}</i></p>`;
  }

  private async getToken(): Promise<string> {
    if (this.accessToken && Date.now() < this.tokenExpiresAt - 60000) {
      return this.accessToken;
    }

    const tokenUrl = `https://login.microsoftonline.com/${encodeURIComponent(this.tenantId)}/oauth2/v2.0/token`;

    const params = new URLSearchParams();
    params.append('client_id', this.clientId);
    params.append('client_secret', this.clientSecret);
    params.append('scope', 'https://graph.microsoft.com/.default');
    params.append('grant_type', 'client_credentials');

    const response = await fetch(tokenUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: params.toString(),
      signal: AbortSignal.timeout(15000),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Graph auth token request failed: ${response.status} ${errorText.slice(0, 200)}`);
    }

    const data = await response.json() as GraphTokenResponse;
    this.accessToken = data.access_token;
    this.tokenExpiresAt = Date.now() + data.expires_in * 1000;

    return this.accessToken;
  }
}
